services:
#  rabbitmq:
#    build:
#      context: ./middleware
#      dockerfile: Dockerfile
#    ports:
#      - 15672:15672
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:15672"]
#        interval: 10s
#        timeout: 5s
#        retries: 10

  distributor:
      build:
        context: .
        dockerfile: distributor/Dockerfile
      restart: on-failure
      environment:
        - PYTHONUNBUFFERED=1

        - PRODUCE_QUEUE_Q1=q11
        - CONSUME_QUEUE_Q1=q14

        - PRODUCE_QUEUE_Q2_1=q211
        - CONSUME_QUEUE_Q2_1=q251
        - JOIN_QUEUE_Q21_1=j211
        - JOIN_QUEUE_Q21_2=j212

        - PRODUCE_QUEUE_Q2_2=q212
        - CONSUME_QUEUE_Q2_2=q232

        - PRODUCE_QUEUE_Q3=q31
        - CONSUME_QUEUE_Q3=q34
        - JOIN_QUEUE_Q3.1=j31
        - JOIN_QUEUE_Q3.2=j32

        - PRODUCE_QUEUE_Q4=q41
        - CONSUME_QUEUE_Q4=q46
        - JOIN_QUEUE_Q4_1=j41
        - JOIN_QUEUE_Q4_1_2=j412
        - JOIN_QUEUE_Q4_2=j42
        - JOIN_QUEUE_Q4_2_2=j422
      networks:
        - mynet
      volumes:
        - ./config.ini:/app/config.ini

#QUERY 21

  filter-q21.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q211
      - PRODUCE_QUEUE=q221

      - COORDINATOR_PRODUCE_QUEUE=Q21C1
      - COORDINATOR_CONSUME_QUEUE=Q21F11

      - FILTER_NAME=byyear
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q21.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q211
      - PRODUCE_QUEUE=q221

      - COORDINATOR_PRODUCE_QUEUE=Q21C1
      - COORDINATOR_CONSUME_QUEUE=Q21F12

      - FILTER_NAME=byyear
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q21.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q21.f1.1
      - filter-q21.f1.2
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q21C1
      - PRODUCE_QUEUE_1=Q21F11
      - PRODUCE_QUEUE_2=Q21F12

      - DOWNSTREAM_QUEUE=q221
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  aggregator-q21.1:
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1

      - CONSUME_QUEUE=q221
      - PRODUCE_QUEUE=q231
      - COUNT_NAME=purchases_qty
      - AGGREGATOR_NAME=sum

      - KEY_COLUMN=item_id
      - VALUE_COLUMN=quantity
      - BUCKET_KIND=month
      - BUCKET_NAME=year_month
      - TIME_COL=created_at
      - OUT_VALUE=total_quantity
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  reducer-q21:
      build:
        context: .
        dockerfile: reducer/Dockerfile
      restart: on-failure

      environment:
        - PYTHONUNBUFFERED=1

        - CONSUME_QUEUE=q231
        - PRODUCE_QUEUE=q241
        - TOP=1
        - COLUMN_NAME=year_month,item_id,total_quantity
      volumes:
        - ./config.ini:/app/config.ini
      networks:
        - mynet

  joiner-q21.j1.1:
      build:
        context: .
        dockerfile: joinner/Dockerfile
      restart: on-failure
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE=q241
        - PRODUCE_QUEUE=q251

        - JOIN_QUEUE=j211
        - COORDINATOR_PRODUCE_QUEUE=Q21C2
        - COORDINATOR_CONSUME_QUEUE=Q21j1

        - COLUMN_NAME=item_name
        - COLUMN_ID=item_id
        - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
      networks:
        - mynet
      volumes:
        - ./config.ini:/app/config.ini

  joiner-q21.j1.2:
      build:
        context: .
        dockerfile: joinner/Dockerfile
      restart: on-failure
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE=q241
        - PRODUCE_QUEUE=q251

        - JOIN_QUEUE=j212
        - COORDINATOR_PRODUCE_QUEUE=Q21C2
        - COORDINATOR_CONSUME_QUEUE=Q21j2

        - COLUMN_NAME=item_name
        - COLUMN_ID=item_id
        - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
      networks:
        - mynet
      volumes:
        - ./config.ini:/app/config.ini

  coordinator-q21.2:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - joiner-q21.j1.1
      - joiner-q21.j1.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2

      - CONSUME_QUEUE=Q21C2
      - PRODUCE_QUEUE_1=Q21j1
      - PRODUCE_QUEUE_2=Q21j2

      - DOWNSTREAM_QUEUE=q251
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

#Query 22

  filter-q22.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q212
      - PRODUCE_QUEUE=q222

      - COORDINATOR_PRODUCE_QUEUE=Q22C1
      - COORDINATOR_CONSUME_QUEUE=Q22F11

      - FILTER_NAME=byyear
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q22.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q212
      - PRODUCE_QUEUE=q222

      - COORDINATOR_PRODUCE_QUEUE=Q22C1
      - COORDINATOR_CONSUME_QUEUE=Q22F12

      - FILTER_NAME=byyear
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q22.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q22.f1.1
      - filter-q22.f1.2
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q22C1
      - PRODUCE_QUEUE_1=Q22F11
      - PRODUCE_QUEUE_2=Q22F12

      - DOWNSTREAM_QUEUE=q222
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini


  aggregator-q22.1:
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1

      - CONSUME_QUEUE=q222
      - PRODUCE_QUEUE=q232
      - COUNT_NAME=earnings
      - AGGREGATOR_NAME=sum

      - KEY_COLUMN=item_id
      - VALUE_COLUMN=subtotal
      - BUCKET_KIND=month
      - BUCKET_NAME=year_month
      - TIME_COL=created_at
      - OUT_VALUE=total_earnings
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet


  # QUERY #1
  filter-q1.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C1
      - COORDINATOR_CONSUME_QUEUE=F11
      
      - FILTER_NAME=bytime
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini
  
  filter-q1.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C1
      - COORDINATOR_CONSUME_QUEUE=F12
      
      - FILTER_NAME=bytime
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q1.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q1.f1.1
      - filter-q1.f1.2
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C1
      - PRODUCE_QUEUE_1=F11
      - PRODUCE_QUEUE_2=F12

      - DOWNSTREAM_QUEUE=q12
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini


  filter-q1.f2.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C2
      - COORDINATOR_CONSUME_QUEUE=F21
      
      - FILTER_NAME=byamount
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f2.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C2
      - COORDINATOR_CONSUME_QUEUE=F22
      
      - FILTER_NAME=byamount
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q1.2:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q1.f1.1
      - filter-q1.f1.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C2
      - PRODUCE_QUEUE_1=F21
      - PRODUCE_QUEUE_2=F22

      - DOWNSTREAM_QUEUE=q13
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini


  filter-q1.f3.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
      - PRODUCE_QUEUE=q14
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C3
      - COORDINATOR_CONSUME_QUEUE=F31

      - FILTER_NAME=bycolumn
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f3.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
      - PRODUCE_QUEUE=q14
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C3
      - COORDINATOR_CONSUME_QUEUE=F32

      - FILTER_NAME=bycolumn
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q1.3:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q1.f3.1
      - filter-q1.f3.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C3
      - PRODUCE_QUEUE_1=F31
      - PRODUCE_QUEUE_2=F32

      - DOWNSTREAM_QUEUE=q14
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini



# QUERIE #3
  aggregator-q3:
      build:
        context: .
        dockerfile: aggregator/Dockerfile
      restart: on-failure
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE=q32
        - PRODUCE_QUEUE=q33
        - AGGREGATOR_NAME=sum
        - KEY_COLUMN=store_id
        - VALUE_COLUMN=final_amount
        - BUCKET_KIND=semester
        - BUCKET_NAME=year_semester
        - TIME_COL=created_at
        - OUT_VALUE=tpv
      networks:
        - mynet
      volumes:
        - ./config.ini:/app/config.ini

  joiner-q3.j1.1:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q33
      - PRODUCE_QUEUE=q34

      - JOIN_QUEUE=j31
      - COORDINATOR_PRODUCE_QUEUE=Q3C2
      - COORDINATOR_CONSUME_QUEUE=Q3j1

      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  joiner-q3.j1.2:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q33
      - PRODUCE_QUEUE=q34

      - JOIN_QUEUE=j32
      - COORDINATOR_PRODUCE_QUEUE=Q3C2
      - COORDINATOR_CONSUME_QUEUE=Q3j2

      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q3.2:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - joiner-q3.j1.1
      - joiner-q3.j1.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2

      - CONSUME_QUEUE=Q3C2
      - PRODUCE_QUEUE_1=Q3j1
      - PRODUCE_QUEUE_2=Q3j2

      - DOWNSTREAM_QUEUE=q34
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q3.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q31
      - PRODUCE_QUEUE=q32
      
      - COORDINATOR_PRODUCE_QUEUE=Q3C1
      - COORDINATOR_CONSUME_QUEUE=Q3F11
      - FILTER_NAME=bytime
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  filter-q3.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q31
      - PRODUCE_QUEUE=q32
      
      - COORDINATOR_PRODUCE_QUEUE=Q3C1
      - COORDINATOR_CONSUME_QUEUE=Q3F12
      - FILTER_NAME=bytime
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q3.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q3.f1.1
      - filter-q3.f1.2
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q3C1
      - PRODUCE_QUEUE_1=Q3F11
      - PRODUCE_QUEUE_2=Q3F12

      - DOWNSTREAM_QUEUE=q32
    networks:
      - mynet
    volumes:
      - ./config.ini:/app/config.ini


# QUERIE #4

  filter-q4.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q41
      - PRODUCE_QUEUE=q42

      - COORDINATOR_PRODUCE_QUEUE=Q4C1
      - COORDINATOR_CONSUME_QUEUE=Q4F11
      - FILTER_NAME=byyear
    networks:
      - mynet

  filter-q4.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q41
      - PRODUCE_QUEUE=q42

      - COORDINATOR_PRODUCE_QUEUE=Q4C1
      - COORDINATOR_CONSUME_QUEUE=Q4F12
      - FILTER_NAME=byyear
    networks:
      - mynet

  coordinator-q4.f1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - filter-q4.f1.1
      - filter-q4.f1.2
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q4C1
      - PRODUCE_QUEUE_1=Q4F11
      - PRODUCE_QUEUE_2=Q4F12

      - DOWNSTREAM_QUEUE=q42

    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  aggregator-q4:
      build:
        context: .
        dockerfile: aggregator/Dockerfile
      restart: on-failure

      environment:
        - PYTHONUNBUFFERED=1

        - CONSUME_QUEUE=q42
        - PRODUCE_QUEUE=q43
        - KEY_COLUMNS=store_id,user_id
        - COUNT_NAME=purchases_qty
        - AGGREGATOR_NAME=counter
      volumes:
        - ./config.ini:/app/config.ini
      networks:
        - mynet

  reducer-q4:
      build:
        context: .
        dockerfile: reducer/Dockerfile
      restart: on-failure

      environment:
        - PYTHONUNBUFFERED=1

        - CONSUME_QUEUE=q43
        - PRODUCE_QUEUE=q44
        - TOP=3
        - COLUMN_NAME=store_id,user_id,purchases_qty
      volumes:
        - ./config.ini:/app/config.ini
      networks:
        - mynet

  joiner-q4.j1.1:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q44
      - PRODUCE_QUEUE=q45

      - JOIN_QUEUE=j41
      - COORDINATOR_PRODUCE_QUEUE=Q4C2
      - COORDINATOR_CONSUME_QUEUE=Q4J11

      - COLUMN_NAME=birthdate
      - COLUMN_ID=user_id
      - USE_DISKCACHE='True' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  joiner-q4.j1.2:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q44
      - PRODUCE_QUEUE=q45

      - JOIN_QUEUE=j412
      - COORDINATOR_PRODUCE_QUEUE=Q4C2
      - COORDINATOR_CONSUME_QUEUE=Q4J12

      - COLUMN_NAME=birthdate
      - COLUMN_ID=user_id
      - USE_DISKCACHE='True' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  coordinator-q4.j1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - joiner-q4.j1.1
      - joiner-q4.j1.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q4C2
      - PRODUCE_QUEUE_1=Q4J11
      - PRODUCE_QUEUE_2=Q4J12

      - DOWNSTREAM_QUEUE=q45

    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet


  joiner-q4.j2.1:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q45
      - PRODUCE_QUEUE=q46

      - JOIN_QUEUE=j42
      - COORDINATOR_PRODUCE_QUEUE=Q4C3
      - COORDINATOR_CONSUME_QUEUE=Q4J21

      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  joiner-q4.j2.2:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure

    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q45
      - PRODUCE_QUEUE=q46

      - JOIN_QUEUE=j422
      - COORDINATOR_PRODUCE_QUEUE=Q4C3
      - COORDINATOR_CONSUME_QUEUE=Q4J22

      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet

  coordinator-q4.j2:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - joiner-q4.j2.1
      - joiner-q4.j2.2

    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q4C3
      - PRODUCE_QUEUE_1=Q4J21
      - PRODUCE_QUEUE_2=Q4J22

      - DOWNSTREAM_QUEUE=q46

    volumes:
      - ./config.ini:/app/config.ini
    networks:
      - mynet


# cliente

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: on-failure
    depends_on:
      - distributor
    links:
      - distributor
    environment:
      - PYTHONUNBUFFERED=1
      - DISTRIBUTOR_HOST=distributor
      - DISTRIBUTOR_PORT=5000
    volumes:
      - ./csvs_files:/app/csvs_files
      - ./results:/app/results
      - ./config.ini:/app/config.ini
    networks:
      - mynet

networks:
  mynet:
    external: false
    driver: bridge