version: '3.8'
services:
  rabbitmq:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  filter:
    build:
      context: ./filter
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
