version: '3.8'
services:
  rabbitmq:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  distributor:
      build:
        context: .
        dockerfile: distributor/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1

        - PRODUCE_QUEUE_Q1=q11
        - CONSUME_QUEUE_Q1=q14

        - PRODUCE_QUEUE_Q3=q31
        - CONSUME_QUEUE_Q3=q34
        - JOIN_QUEUE_Q3=j31

        - PRODUCE_QUEUE_Q4=q41
        - CONSUME_QUEUE_Q4=q45
        - JOIN_QUEUE_Q4_1=j41
        - JOIN_QUEUE_Q4_2=j42

      volumes:
        - ./config.ini:/app/config.ini


# QUERIE #1

  filter-q1.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C1
      - COORDINATOR_CONSUME_QUEUE=F1.1
      
      - FILTER_NAME=bytime
    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C1
      - COORDINATOR_CONSUME_QUEUE=F1.2
      
      - FILTER_NAME=bytime
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q1.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - filter-q1.f1.1
      - filter-q1.f1.2

    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C1
      - PRODUCE_QUEUE_1=F1.1
      - PRODUCE_QUEUE_2=F1.2

      - DOWNSTREAM_QUEUE=q12

    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f2.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13

      - COORDINATOR_PRODUCE_QUEUE=Q1C2
      - COORDINATOR_CONSUME_QUEUE=F2.1

      - FILTER_NAME=byamount
    volumes:
      - ./config.ini:/app/config.ini
  
  filter-q1.f2.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C2
      - COORDINATOR_CONSUME_QUEUE=F2.2

      - FILTER_NAME=byamount
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-q1.2:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - filter-q1.f2.1
      - filter-q1.f2.2

    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C2
      - PRODUCE_QUEUE_1=F2.1
      - PRODUCE_QUEUE_2=F2.2

      - DOWNSTREAM_QUEUE=q13

    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f3.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
      - PRODUCE_QUEUE=q14
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C3
      - COORDINATOR_CONSUME_QUEUE=F3.1

      - FILTER_NAME=bycolumn
    volumes:
      - ./config.ini:/app/config.ini

  filter-q1.f3.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
      - PRODUCE_QUEUE=q14
      
      - COORDINATOR_PRODUCE_QUEUE=Q1C3
      - COORDINATOR_CONSUME_QUEUE=F3.2

      - FILTER_NAME=bycolumn
    volumes:
      - ./config.ini:/app/config.ini

  coordinator-1.3:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - filter-q1.f3.1
      - filter-q1.f3.2

    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q1C3
      - PRODUCE_QUEUE_1=F3.1
      - PRODUCE_QUEUE_2=F3.2

      - DOWNSTREAM_QUEUE=q14

    volumes:
      - ./config.ini:/app/config.ini


# QUERIE #3
  aggregator-q3:
      build:
        context: .
        dockerfile: aggregator/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE=q32
        - PRODUCE_QUEUE=q33
        - AGGREGATOR_NAME=tpv_by_semester_store
      volumes:
        - ./config.ini:/app/config.ini

  joiner-q3:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q33
      - PRODUCE_QUEUE=q34
      - JOIN_QUEUE=j31
      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini
  
  filter-q3.f1.1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q31
      - PRODUCE_QUEUE=q32   

      - COORDINATOR_PRODUCE_QUEUE=Q3C1
      - COORDINATOR_CONSUME_QUEUE=F1.1

      - FILTER_NAME=bytime

  filter-q3.f1.2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q31
      - PRODUCE_QUEUE=q32   

      - COORDINATOR_PRODUCE_QUEUE=Q3C1
      - COORDINATOR_CONSUME_QUEUE=F1.2

      - FILTER_NAME=bytime

  coordinator-3.1:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - filter-q3.f1.1
      - filter-q3.f1.2

    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - NUM_NODES=2
      - CONSUME_QUEUE=Q3C1
      - PRODUCE_QUEUE_1=F1.1
      - PRODUCE_QUEUE_2=F1.2
      - DOWNSTREAM_QUEUE=q32

    volumes:
      - ./config.ini:/app/config.ini

# QUERIE #4
  aggregator-q4:
      build:
        context: .
        dockerfile: aggregator/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1

        - CONSUME_QUEUE=q41
        - PRODUCE_QUEUE=q42
        - AGGREGATOR_NAME=counter
      volumes:
        - ./config.ini:/app/config.ini

  reducer-q4:
      build:
        context: .
        dockerfile: reducer/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1

        - CONSUME_QUEUE=q42
        - PRODUCE_QUEUE=q43
        - TOP=7
        - COLUMN_NAME=store_id,user_id,purchases_qty
      volumes:
        - ./config.ini:/app/config.ini

  joiner-q4.1:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q43
      - PRODUCE_QUEUE=q44

      - JOIN_QUEUE=j41
      - COLUMN_NAME=birthdate
      - COLUMN_ID=user_id
      - USE_DISKCACHE=True # True sin comillas y con mayusucula
    volumes:
      - ./config.ini:/app/config.ini

  joiner-q4.2:
    build:
      context: .
      dockerfile: joinner/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q44
      - PRODUCE_QUEUE=q45

      - JOIN_QUEUE=j42
      - COLUMN_NAME=store_name
      - COLUMN_ID=store_id
      - USE_DISKCACHE='' # string vacio == false, cualquier otro valor == true
    volumes:
      - ./config.ini:/app/config.ini

# cliente

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - distributor
    links:
      - rabbitmq
      - distributor
    environment:
      - PYTHONUNBUFFERED=1
      - DISTRIBUTOR_HOST=distributor
      - DISTRIBUTOR_PORT=5000
    volumes:
      - ./csvs_files:/app/csvs_files
      - ./results:/app/results
      - ./config.ini:/app/config.ini
