version: '3.8'
services:
  rabbitmq:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  distributor:
      build:
        context: .
        dockerfile: distributor/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE_Q1=q14
        - PRODUCE_QUEUE_Q1=q11

        - CONSUME_QUEUE_Q3=q33
        - PRODUCE_QUEUE_Q3=q31
      volumes:
        - ./config.ini:/app/config.ini

  aggregator_q3:
      build:
        context: .
        dockerfile: aggregator/Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1
        - CONSUME_QUEUE=q32
        - PRODUCE_QUEUE=q33
        - AGGREGATOR_NAME=tpv_by_semester_store

  # reducer_q3_join:
  #   build:
  #     context: .
  #     dockerfile: reducer/Dockerfile
  #   restart: on-failure
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - CONSUME_QUEUE=q33
  #     - PRODUCE_QUEUE=q34
  #     - REDUCER_NAME=join_stores
  #     - STORES_CSV=/app/csvs_files/stores.csv
  #   volumes:
  #     - ./csvs_files:/app/csvs_files
  #     - ./config.ini:/app/config.ini


  filter1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      - FILTER_NAME=bytime
    volumes:
      - ./config.ini:/app/config.ini

  filter2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13
      - FILTER_NAME=byamount
    volumes:
      - ./config.ini:/app/config.ini

  filter3:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
      - PRODUCE_QUEUE=q14
      - FILTER_NAME=bycolumn
    volumes:
      - ./config.ini:/app/config.ini

  filter_time1_q3:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q31
      - PRODUCE_QUEUE=q32
      - FILTER_NAME=bytime
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - distributor
    links:
      - rabbitmq
      - distributor
    environment:
      - PYTHONUNBUFFERED=1
      - DISTRIBUTOR_HOST=distributor
      - DISTRIBUTOR_PORT=5000
    volumes:
      - ./csvs_files:/app/csvs_files
      - ./results:/app/results
      - ./config.ini:/app/config.ini
