version: '3.8'
services:
  rabbitmq:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCE_QUEUE=q11
    volumes:
      - ./trans.csv:/app/trans.csv

  filter1:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q11
      - PRODUCE_QUEUE=q12
      - FILTER_NAME=bytime

  filter2:
    build:
      context: .
      dockerfile: filter/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q12
      - PRODUCE_QUEUE=q13
      - FILTER_NAME=byamount
      
  reducer:
    build:
      context: .
      dockerfile: reducer/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUME_QUEUE=q13
