services:
  
 distributor:
  build:
   context: .
   dockerfile: distributor/Dockerfile
  restart: on-failure
  environment:
   - PYTHONUNBUFFERED=1
   - PRODUCE_QUEUE_Q1=q11
   - CONSUME_QUEUE_Q1=q14
   - PRODUCE_QUEUE_Q3=q31
   - CONSUME_QUEUE_Q3=q34
   - PRODUCE_QUEUE_Q4=q41
   - CONSUME_QUEUE_Q4=q46
   - JOIN_QUEUE_Q3.1=j31
   - JOIN_QUEUE_Q4.1.1=j411
   - JOIN_QUEUE_Q4.1.2=j412
   - JOIN_QUEUE_Q3.2=j32
   - JOIN_QUEUE_Q4.2.1=j421
   - JOIN_QUEUE_Q4.2.2=j422
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 filter-q1.f1.1:
  build:
   context: .
   dockerfile: filter/Dockerfile
  restart: on-failure
  environment:
   - PYTHONUNBUFFERED=1
   - CONSUME_QUEUE=q11
   - PRODUCE_QUEUE=q12

   - COORDINATOR_PRODUCE_QUEUE=Q1C1
   - COORDINATOR_CONSUME_QUEUE=F11

   - FILTER_NAME=bytime
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 filter-q1.f1.2:
  build:
   context: .
   dockerfile: filter/Dockerfile
  restart: on-failure
  environment:
   - PYTHONUNBUFFERED=1
   - CONSUME_QUEUE=q11
   - PRODUCE_QUEUE=q12

   - COORDINATOR_PRODUCE_QUEUE=Q1C1
   - COORDINATOR_CONSUME_QUEUE=F12

   - FILTER_NAME=bytime
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 coordinator-q1.1:
  build:
   context: .
   dockerfile: coordinator/Dockerfile
  restart: on-failure
  depends_on:
    - filter-q1.f1.1
    - filter-q1.f1.2
  environment:
   - PYTHONUNBUFFERED=1
   - NUM_NODES=2
   - CONSUME_QUEUE=Q1C1
    - PRODUCE_QUEUE_1=F11
    - PRODUCE_QUEUE_2=F12
   - DOWNSTREAM_QUEUE=q12
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 filter-q1.f2.1:
  build:
   context: .
   dockerfile: filter/Dockerfile
  restart: on-failure
  environment:
   - PYTHONUNBUFFERED=1
   - CONSUME_QUEUE=q12
   - PRODUCE_QUEUE=q13

   - COORDINATOR_PRODUCE_QUEUE=Q1C2
   - COORDINATOR_CONSUME_QUEUE=F21

   - FILTER_NAME=byamount
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 filter-q1.f2.2:
  build:
   context: .
   dockerfile: filter/Dockerfile
  restart: on-failure
  environment:
   - PYTHONUNBUFFERED=1
   - CONSUME_QUEUE=q12
   - PRODUCE_QUEUE=q13

   - COORDINATOR_PRODUCE_QUEUE=Q1C2
   - COORDINATOR_CONSUME_QUEUE=F22

   - FILTER_NAME=byamount
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini

 coordinator-q1.2:
  build:
   context: .
   dockerfile: coordinator/Dockerfile
  restart: on-failure
  depends_on:
    - filter-q1.f2.1
    - filter-q1.f2.2
  environment:
   - PYTHONUNBUFFERED=1
   - NUM_NODES=2
   - CONSUME_QUEUE=Q1C1
    - PRODUCE_QUEUE_1=F21
    - PRODUCE_QUEUE_2=F22
   - DOWNSTREAM_QUEUE=q12
  networks:
   - mynet
  volumes:
   - ./config.ini:/app/config.ini
